-- Clear the diagnostic warnings, this is generated by the flake before getting here.
PluginsFromNix = PluginsFromNix or {}

require 'options'
require 'keymap'
require 'autocmd'

require('lazy').setup({
	performance = {
		rtp = {
			reset = false,
			disabled_plugins = {
				'gzip',
				'matchit',
				'netrw',
				'netrwPlugin',
				'tarPlugin',
				'tohtml',
				'tutor',
				'zipPlugin'
			},
		},
	},
	spec = { import = 'plugins' }
})

vim.cmd [[ colorscheme catppuccin ]]
